name: Go

on:
  schedule:
    - cron: '30 16 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Run
      env: 
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      run: go run main.go

